### ISSUE TITLE
ErrorCode 127 Fault Injection w/ OSError: [ErrNo 22] Invalid Argument in target infra_agent.log

### ISSUE THREAD

**Issue by xanderLum** [vmware/mangle#116]
Hi Mangle Team,

I'm currently testing VMWare mangle in my environment without internet connectivity and I've been encountering **error code 127 output: ./infra_submit: error while loading shared libraries: libz.so.1: failed to map segment from shared object** when injecting CPU fault to target server from Mangle portal.

I have attached 2 log files here: 
1. mangle-services-app.logfile (20220718.txt file)
2. target server infra_agent log file (infra_agent.txt) file

for your reference as I'm currently stuck on what's causing this issue.  Appreciate your help on this, thank you in advance!

Xander

[20220718.txt](https://github.com/vmware/mangle/files/9131257/20220718.txt)
[infra_agent.log](https://github.com/vmware/mangle/files/9131258/infra_agent.log)

**Comment by ashrimalivmware** [comment]
Hi @xanderLum, Looking into the issue, will update you.

**Comment by georgephilif** [comment]
Hi @xanderLum,
In order to startup mangle agent, and inject faults on a target machine, the '/tmp' directory on the target machine should be mounted with exec permissions.
You can either,
1. Remount '/tmp' with exec permissions
`sudo mount /tmp -o remount,exec`
or
2. Set TMP to a different directory where you have exec permissions
`export TMP=<your-dir>`

**Comment by xanderLum** [comment]
> 

Hi @georgephilif , may I know for option 2:
Set TMP to a different directory where you have exec permissions
export TMP=<your-dir>

understand this is executed in the target endpoint, may I know if this TMP will need to be run 1 time on every target endpoint to setup to my home directory where I have exec permissions?

Thank you

**Comment by georgephilif** [comment]
Hi @xanderLum,
Currently yes, the Mangle agent requires a TMP directory with 'exec' permissions on the target to inject faults. 
We'll also try to work on removing this prerequisite, as part of future releases.
