### ISSUE TITLE
Mangle EndPoint Creation Failure

### ISSUE THREAD

**Issue by soonrita-i** [vmware/mangle#142]
Hello @rpraveen-vmware @ranjansvmware,

We have mangle installed in our AWS EKS cluster(v1.25). Mangle pods are up and running. However, when trying to create an endpoint we have encountered the below error.

_Test Connection failed for endpoint, Please verify the credentials {0}. Reason: Test Connection failed for endpoint, Please reverify the credentials._

Mangle and the endpoint app to which we are trying to connect are both in the same cluster. The endpoint app is also up.

Steps followed to create an endpoint.

1. Endpoint -> Credentials -> Endpoint Credentials
2. Endpoint -> Endpoints -> Kubernetes Cluster -> Added the endpoint name, selected the credential name from dropdown created in Step1, updated the namespace name and performed test connection.

Could you please check and let us know?

Thank you!

**Comment by rpraveen-vmware** [comment]
Hi Abhinandan/ Sowmya,    
 As I understand, the namespace you are trying to add in endpoint seems like having restricted permissions to communicate from pods of other namespace. Hence, Mangle pod is unable to add this namespace as part of endpoint.
To cross check this, exec inside mangle pod and try executing the below commands to see the actual error.

   kubectl -n <namespace> get all
   kubectl -n <namespace> get pods.

Let me know if you need any additional assistance.

Regards,
Praveen R

**Comment by rpraveen-vmware** [comment]
Hi @soonrita-i ,
Let me know if you are able to proceed on this.

**Comment by soonrita-i** [comment]
Thank you Praveen for your inputs. We were able to bypass the error now.

Soonrita

**Comment by rpraveen-vmware** [comment]
Great to know this @soonrita-i 
Will resolve this ticket.

**Comment by rpraveen-vmware** [comment]
@soonrita-i , 
Also please mention here if any steps (apart from the above mentioned) if you had to follow to resolve the error.
cc: @ranjansvmware
