### ISSUE TITLE
API auth type?

### ISSUE THREAD

**Issue by robglas** [vmware/mangle#24]
**Describe the bug**
Looking to use the APIs. Found the Swagger spec, but unclear what auth type is used.

Tried using basic auth, but that doesn't appear to be it. Not finding any OAuth-related APIs either, so unable to retrieve a token (or create one via the UI).

```
"timestamp": 1579295166847,
"code": "FI0132",
"description": "Invalid username or password",
"details": "/mangle-services/rest/api/v1/metric-provider-controller/"

```
**To Reproduce**
1. Load any API, i.e. https://host/mangle-services/rest/api/v1/metric-provider-controller/?metricProviderByStatus=ALL

**Expected behavior**
An API response is returned.

**Comment by chethanvmware** [comment]
The auth type is basic auth. 

You need to use username as <username>@<domain-name>(mangle.local: if you are using local users). I guess that could be the issue because of which you are running into this.

**Comment by vhkilari** [comment]
Hi @robglas,
                       Can you close the issue, if you find the reply from @chethanvmware has resolved your issue?
Thanks,
    -Hemanth K

**Comment by robglas** [comment]
Will do. I tried Basic Auth before I submitted this and that didn't work, but I was using Postman. 
I'll give it another shot tomorrow.
