### ISSUE TITLE
Build fails due to dependencies from VMware Eng repo

### ISSUE THREAD

**Issue by amalts** [vmware/mangle#31]
**Describe the bug**

**To Reproduce**
module : om.vmware.mangle:mangle-models
mvn install

**Logs**
`Could not transfer artifact com.fasterxml.jackson.datatype:jackson-datatype-joda:pom:2.11 from/to build-artifactory.eng.vmware.com (https://build-artifactory.eng.vmware.com/artifactory/fiaasco-release): build-artifactory.eng.vmware.com: nodename nor servname provided, or not known
`

**Comment by bhanukiran-karanam** [comment]
We accepted this bug and working on the fix.

**Comment by chethanvmware** [comment]
Hi, 
we are actively working on resolving the issue.
Meanwhile, as a workaround can you remove the repository entries(related to https://build-artifactory.eng.vmware.com) in pom.xml under the mangle directory?

To be specific, remove the repository of entry mentioned between 28 and 33, and 129 and 134

This should unblock you for now.
