### ISSUE TITLE
Can't connect to Mangle UI

### ISSUE THREAD

**Issue by zwaris66** [vmware/mangle#39]
I am getting the following error:

Bad Request
This combination of host and port requires TLS.

**Comment by avishrimali** [comment]
Hi,

Can you please explain a bit more about the issue? Like what mode you have selected to deploy mangle Docker/K8S or ova, and system logs, screenshot etc.
Thanks,
-Avinash

**Comment by zwaris66** [comment]
I deployed it in K8s v1.16. i can coonect to it if do;
C:\Users\468569>kubectl port-forward svc/mangle-service 8000:8443 -n mangle 
from my PC but can connect to it via internet.

**Comment by avishrimali** [comment]
It looks like the mangle service url is not public facing. If you are able to access mangle via port forwarding then it must be some configuration issue with k8s cluster configuration.

Thanks,
-Avinash

**Comment by zwaris66** [comment]
Thanks, Avinash! BTW, it is possible to have a conference call to troubleshoot this issue?

Zee
________________________________

**Comment by ashrimalivmware** [comment]
Sure please let me know the suitable timings, will schedule one.

**Comment by zwaris66** [comment]
Great! which time zone are you in? i am in US Central (Texas).

Thx!
Zee
________________________________

**Comment by ashrimalivmware** [comment]
Hi Zee, I am in IST time zone.

**Comment by zwaris66** [comment]
What time do you start your day? I can set up a meeting late at night my time.

Thanks!
Zee
________________________________

**Comment by ashrimalivmware** [comment]
Sure Zee, can we do it tomorrow evening i.e. morning hours your time?
cc @rpraveen-vmware

**Comment by ashrimalivmware** [comment]
Hi @zwaris66 Closing this issue as per our last conversation.
