### ISSUE TITLE
Java Method Latency Not Working

### ISSUE THREAD

**Issue by anuanju89** [vmware/mangle#46]
**Describe the bug**
When I execute Java Method Latency fault with 20,000ms latency at specific method and class from mangle application, it is showing in logs that "Completed Fault Injection". However when I make a manual API call to the service, I do not observe any latency close to 20 seconds added to service response. The response time of this API without Network latency is typically ~5 seconds and are able to verify in Application logs that it invokes the target Java Class and Method. I was able to successfully execute other Application Fault – Java - Burn CPU on target JVM process running on K8s POD and able to observe spike in JVM process CPU utilization. However I am unable to execute Application Fault - Java method latency successfully. 

**To Reproduce**
1. Go to 'Mangle Application -> Login -> Fault Execution -> Application Faults -> Java Method Latency'
2. Enter All the details - K8s endpoint, Class, Method, Latency (20,000 ms), Rule Event, K8s arguments and JVM Properties of a springboot service
3. Click on 'Run Fault'
4. Go to Requests and Reports - 'Wait for the Fault to Complete by clicking the refresh button'
5. Now Test the service(Which will hit the class and method mentioned in step 2) by making manual API call using postman or curl command and check its response time.

**Expected behavior**
The response of the service should be > 20,000ms.

**Screenshots**

**Logs**
If applicable, add application logs/troubleshooting bundle to help in root cause analysis.
2020-12-22 17:01:15.009 [BytemanFaultTaskHelper-1608656456217-1] INFO  com.vmware.mangle.task.framework.helpers.AbstractCommandExecutionTaskHelper.triggerFaultInjectionStage (165) - Completed Fault Injection

**Configuration information:**
 - Deployment Type: Container
 - Deployment Mode: Single Node
 - Client OS: Windows
 - Client Browser: Chrome
 - Version: 84.0.4147.125
 
**Additional context**
We tried to debug this by reviewing the Mangle agent processes created on POD and observed multiple parent and child processes spawned by mangle on target POD. We also notice that all these processes are terminated in ~5 seconds of Chaos test execution. 

jboss      4104      0  5 06:20 ?        00:00:00 tar -xmf - -C /tmp/mangle-java-agent-2.0.0
jboss      4118      0  0 06:20 ?        00:00:00 /bin/sh -c export JAVA_HOME=<Path to Java Home> && /tmp/mangle-java-agent-2.0.0/bin/bminstall.sh -p 9091 -s -b 639
jboss      4125   4118  0 06:20 ?        00:00:00 /bin/bash /tmp/mangle-java-agent-2.0.0/bin/bminstall.sh -p 9091 -s -b 639
jboss      4126   4125  0 06:20 ?        00:00:00 /bin/bash /tmp/mangle-java-agent-2.0.0/bin/bminstall.sh -p 9091 -s -b 639
jboss      4213      0  0 06:20 ?        00:00:00 /bin/sh /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -p 9091 /tmp/mangle-java-agent-2.0.0/70bb3609-d61f-49fb-b025-3f7064c9854d.btm
jboss      4221   4213  0 06:20 ?        00:00:00 <Path to Java Home> /bin/java -classpath /tmp/mangle-java-agent-2.0.0/lib/mangle-byteman.jar:/tmp/mangle-java-agent-2.0.0/lib/mangle-byteman-submit.jar org.jboss.byteman.agent.submit.Submit -p 9091 /tmp/mangle-java-agent-2.0.0/70bb3609-d61f-49fb-b025-3f7064c9854d.btm
 
Since we did not notice any latency induced, we tried to manually re-execute the command “/bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bminstall.sh -p 9091 -s -b 639” on target POD and noticed  that listener was running with an error “Agent is already running on requested process”.

Below is the snippet of output of the command.

/tmp/mangle-java-agent-2.0.0/lib/mangle-byteman.jar
org.jboss.byteman.agent.FiaascoTransformListener- I am here on Pid: 639

java.lang.IllegalStateException: Agent is already running on requested process
        at org.jboss.byteman.agent.install.Install.notifyRetriedInstallation(Install.java:98)
        at org.jboss.byteman.agent.install.Install.isPortAvailable(Install.java:75)
        at org.jboss.byteman.agent.install.Install.injectAgent(Install.java:613)
        at org.jboss.byteman.agent.install.Install.main(Install.java:61)

We tried to execute bmsubmit.sh with few options to list the already executed faults or currently running faults, which returned empty list. 

Below is the logs.
sh-4.2$ /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -laf
{}

sh-4.2$ /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -llf
{}

sh-4.2$ /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -gaf
{}

sh-4.2$ pwd
/tmp/mangle-java-agent-2.0.0
sh-4.2$ ls
537eff34-2f04-446c-b7d0-e624b99251e4.btm  bin                                       de583ce6-27cf-400e-9dfa-4df65cc8f0dc.btm  mangle-java-agent-2.0.0
70bb3609-d61f-49fb-b025-3f7064c9854d.btm  c4a0a9e7-e6a6-421e-a68c-8fe8dab1c8ac.btm  fdd9ac8f-2260-4e9b-b3d0-f350b2799a32.btm
a2761878-dd89-48b8-96c4-9ac855f99db3.btm  ddd7ccaf-c062-41a8-9813-02a972a0ebfe.btm  lib
sh-4.2$

**Comment by vhkilari** [comment]
@anuanju89 I appreciate your deep analysis before raising the issue. 
```
sh-4.2$ /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -gaf
{}
```
suggests us that there is no active fault being run by Java Agent now. As the other code faults are getting executed with no issues. There is no issue with application instrumentation by mangle-java-agent. I suggest you try the below steps. we will take further steps based on your feedback.

Try the below command to force the exit of the agent already attached to your process.
`/tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -forceExit`

Now try injecting the fault again using the below commands.
`/bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bminstall.sh -p 9091 -s -b 639`
`/bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -p 9091 /tmp/mangle-java-agent-2.0.0/70bb3609-d61f-49fb-b025-3f7064c9854d.btm`
Now if you are not observing the desired behaviour, please update the issue with output of below commands.
`/bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -p 9091 -gaf`
`/bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -p 9091 -l`
you can mask the classname and method names reported in the output if you feel it is a confidential data.

**Comment by vhkilari** [comment]
@anuanju89 You have dug advanced level information from mangle for helping us to RCA the issue. It demonstrated your expertise in Mangle tool and System Administration. We are hoping to receive 360-degree feedback and contribution from you to make our Mangle more appealing to the chaos engineering community.
Thanks,
    -Hemanth K

**Comment by anuanju89** [comment]
@vhkilari Thank you for the response.
I ran bmsubmit.sh with forceExit option and exiting agent was exit successfully.

I tried re running the fault again using commands, but didn't find "Sleeping" string in my application logs and latency also not induced in the application.
### Few observations on output of fault execution commands.
On execution of bminstall.sh, Listener started, but it says "Cannot locate tools jar". After that I ran bmsubmit.sh, I got "install rule 70bb3609-d61f-49fb-b025-3f7064c9854d" on the last line. 
Out put for bminstall.sh
```
/bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bminstall.sh -p 9091 -s -b 639

Cannot locate tools jar
java -Djava.library.path=/tmp/mangle-java-agent-2.0.0/bin -classpath /tmp/mangle-java-agent-2.0.0/lib/mangle-byteman-install.jar:/tmp/mangle-java-agent-2.0.0/lib/mangle-byteman.jar:/tmp/mangle-java-agent-2.0.0/lib/mangle-byteman-submit.jar:/tmp/mangle-java-agent-2.0.0/lib/tools.jar org.jboss.byteman.agent.install.Install -p 9091 -s -b 639
/tmp/mangle-java-agent-2.0.0/lib/mangle-byteman.jar
Started Byteman Listener Successfully
```

I verified the content in 70bb3609-d61f-49fb-b025-3f7064c9854d.btm file and the helper class is different from what you have provided.
The helper class in my btm file is  ``com.vmware.mangle.java.agent.faults.helpers.BytemanRuleHelper``

I edited btm file and changed that helper class to  ``com.vmware.fiaasco.java.faults.helpers.BytemanRuleHelper``
I followed all the steps - Force exit, re running the fault commands - But still didn't find "Sleeping" string in application and also expected latency was not induced.

I ran the trouble shoot commands provided by you before and after changing the helper class in btm file.
1. gaf option returned empty list for both btm files.
2. l option has thrown exception - unknown helper class
```
org.jboss.byteman.rule.exception.TypeException: Rule.typecheck : unknown helper class com.vmware.fiaasco.java.faults.helpers.BytemanRuleHelper for rule 70bb3609-d61f-49fb-b025-3f7064c9854d
org.jboss.byteman.rule.exception.TypeException: Rule.typecheck : unknown helper class com.vmware.fiaasco.java.faults.helpers.BytemanRuleHelper for rule 70bb3609-d61f-49fb-b025-3f7064c9854d
```

### Output of trouble shoot commands for original btm file (Helper class - com.vmware.mangle.java.agent.faults.helpers.BytemanRuleHelper)

##### gaf option returned empty list

```
sh-4.2$ /bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -p 9091 -gaf

The output has many exports and after exports, below is the output
{}
```
##### l option has thrown exception - unknown helper class
```
sh-4.2$ /bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -p 9091 -l

The output has many exports, below is the output after export
# File /tmp/mangle-java-agent-2.0.0/70bb3609-d61f-49fb-b025-3f7064c9854d.btm line 16
RULE 70bb3609-d61f-49fb-b025-3f7064c9854d
CLASS <FULLY-QUALIFIED-CLASS-NAME>
METHOD <METHOD-NAME>
HELPER com.vmware.mangle.java.agent.faults.helpers.BytemanRuleHelper
NOCOMPILE
AT ENTRY

IF true
DO sleep(20000)
ENDRULE
Transformed in:
loader: ModuleClassLoader for Module "<WAR-FILE-NAME>.war" from Service Module Loader
trigger class: <FULLY QUALIFIED CLASS NAME>
threw org.jboss.byteman.rule.exception.TypeException: Rule.typecheck : unknown helper class com.vmware.mangle.java.agent.faults.helpers.BytemanRuleHelper for rule 70bb3609-d61f-49fb-b025-3f7064c9854d
org.jboss.byteman.rule.exception.TypeException: Rule.typecheck : unknown helper class com.vmware.mangle.java.agent.faults.helpers.BytemanRuleHelper for rule 70bb3609-d61f-49fb-b025-3f7064c9854d
at org.jboss.byteman.rule.Rule.<init>(Rule.java:233)
at org.jboss.byteman.rule.Rule.create(Rule.java:356)
at org.jboss.byteman.agent.TransformContext.parseRule(TransformContext.java:173)
at org.jboss.byteman.agent.TransformContext.transform(TransformContext.java:83)
at org.jboss.byteman.agent.Transformer.transform(Transformer.java:748)
at org.jboss.byteman.agent.Transformer.tryTransform(Transformer.java:815)
at org.jboss.byteman.agent.Transformer.tryTransform(Transformer.java:787)
at org.jboss.byteman.agent.Transformer.transform(Transformer.java:260)
at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at org.jboss.byteman.agent.Retransformer.installScript(Retransformer.java:146)
at org.jboss.byteman.agent.FiaascoTransformListener.handleScripts(FiaascoTransformListener.java:596)
at org.jboss.byteman.agent.FiaascoTransformListener.loadScripts(FiaascoTransformListener.java:514)
at org.jboss.byteman.agent.FiaascoTransformListener.handleConnection(FiaascoTransformListener.java:271)
at org.jboss.byteman.agent.FiaascoTransformListener.run(FiaascoTransformListener.java:202)
```

### Output of trouble shoot commands for MODIFIED btm file (Helper class - com.vmware.fiaasco.java.faults.helpers.BytemanRuleHelper)

##### gaf option returned empty list

```
sh-4.2$ /bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -p 9091 -gaf

The output has many exports and after exports, below is the output
{}
```
##### l option has thrown exception - unknown helper class
```
sh-4.2$ /bin/sh -c export JAVA_HOME=/pkgs/openjdk8 && /tmp/mangle-java-agent-2.0.0/bin/bmsubmit.sh -p 9091 -l

The output has many exports, below is the output after export
# File /tmp/mangle-java-agent-2.0.0/70bb3609-d61f-49fb-b025-3f7064c9854d.btm line 16
RULE 70bb3609-d61f-49fb-b025-3f7064c9854d
CLASS <FULLY-QUALIFIED-CLASS-NAME>
METHOD <METHOD-NAME>
HELPER com.vmware.fiaasco.java.faults.helpers.BytemanRuleHelper
NOCOMPILE
AT ENTRY

IF true
DO sleep(20000)
ENDRULE
Transformed in:
loader: ModuleClassLoader for Module "<WAR-FILE-NAME>.war" from Service Module Loader
trigger class: <FULLY-QUALIFIED-CLASS-NAME>
threw org.jboss.byteman.rule.exception.TypeException: Rule.typecheck : unknown helper class com.vmware.fiaasco.java.faults.helpers.BytemanRuleHelper for rule 70bb3609-d61f-49fb-b025-3f7064c9854d
org.jboss.byteman.rule.exception.TypeException: Rule.typecheck : unknown helper class com.vmware.fiaasco.java.faults.helpers.BytemanRuleHelper for rule 70bb3609-d61f-49fb-b025-3f7064c9854d
at org.jboss.byteman.rule.Rule.<init>(Rule.java:233)
at org.jboss.byteman.rule.Rule.create(Rule.java:356)
at org.jboss.byteman.agent.TransformContext.parseRule(TransformContext.java:173)
at org.jboss.byteman.agent.TransformContext.transform(TransformContext.java:83)
at org.jboss.byteman.agent.Transformer.transform(Transformer.java:748)
at org.jboss.byteman.agent.Transformer.tryTransform(Transformer.java:815)
at org.jboss.byteman.agent.Transformer.tryTransform(Transformer.java:787)
at org.jboss.byteman.agent.Transformer.transform(Transformer.java:260)
at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at org.jboss.byteman.agent.Retransformer.installScript(Retransformer.java:146)
at org.jboss.byteman.agent.FiaascoTransformListener.handleScripts(FiaascoTransformListener.java:596)
at org.jboss.byteman.agent.FiaascoTransformListener.loadScripts(FiaascoTransformListener.java:514)
at org.jboss.byteman.agent.FiaascoTransformListener.handleConnection(FiaascoTransformListener.java:271)
at org.jboss.byteman.agent.FiaascoTransformListener.run(FiaascoTransformListener.java:202)
```

**Comment by anuanju89** [comment]
After executing the faults using commands with modified the btm file, I observed below lines in application logs.
```
05:27:26,670 INFO  [org.jboss.byteman.agent.FiaascoTransformListener] (Thread-108) Trying to Terminate Listener
05:27:26,878 INFO  [org.jboss.byteman.agent.FiaascoTransformListener] (Thread-108) Terminated Listener
05:27:26,879 INFO  [org.jboss.byteman.agent.FiaascoTransformListener] (Thread-108) shutdown Value:true
```

**Comment by vhkilari** [comment]
@anuanju89, Can you try executing the fault? with below btm file contents after replacing the <FULLY-QUALIFIED-CLASS-NAME>, <METHOD-NAME> with your actaul target class name (e.g. javax.servlet.http.HttpServlet) and method name (e.g. service(HttpServletRequest,HttpServletResponse).

RULE 70bb3609-d61f-49fb-b025-3f7064c9854d
CLASS <FULLY-QUALIFIED-CLASS-NAME>
METHOD <METHOD-NAME>
HELPER com.vmware.mangle.java.agent.faults.helpers.BytemanRuleHelper
AT ENTRY
IF true
DO sleep(20000)
ENDRULE

**Comment by anuanju89** [comment]
I have above content only in my btm file. The only difference is new line between AT ENTRY and IF true. I deleted that new line entry and executed fault with the btm file, still did see "Sleeping" string in application logs and latency in the application.
I ran trouble shoot commands and the out is same as above mentioned comment- 
#### Output of trouble shoot commands for original btm file (Helper class - com.vmware.mangle.java.agent.faults.helpers.BytemanRuleHelper)

Below is the content in my btm file (Given the sample representation of method and class names)
```
RULE 70bb3609-d61f-49fb-b025-3f7064c9854d
CLASS com.pkg1.pkg2.pkg3.pkg4.pkg5.pkg6.pkg7.ClassService
METHOD methodName
HELPER com.vmware.mangle.java.agent.faults.helpers.BytemanRuleHelper
AT ENTRY
IF true
DO sleep(20000)
```

Below is the format of my class and method
```
package com.pkg1.pkg2.pkg3.pkg4.pkg5.pkg6.pkg7
import
import
import
.
.
.
.
.
@Component
public class ClassService {
.
.
.
.
.
public List<ClassA> methodName(ClassB varB) throws IllegalArgumentException, IllegalAccessException {
.
.
.
.
}
Other Methods
.
.
.
}
```

I tried executing fault by passing method name as below in btm file - but no luck
Test1 - methodName
Test2 - methodName(ClassB varB)
Test3 - methodName(varB)

**Comment by anuanju89** [comment]
@vhkilari

**Comment by vhkilari** [comment]
Is 'ENDRULE' line missing in your RULE file?

**Comment by anuanju89** [comment]
@vhikilari - ENDRULE is not missing, just I missed pasting that in the comment.

I can do Teams meeting, if that works. Please let me know.

**Comment by vhkilari** [comment]
@anuanju89 Teams meeting will work for me. Let me know, your preferrable time.

**Comment by anuanju89** [comment]
Hi Hemanth,

I would prefer between 9 AM to 11 AM IST on all days.
Please let me know, if that works please share the teams ID.

Thanks
Lakshmi P

**Comment by vhkilari** [comment]
@anuanju89 Please forward your request to mange@vmware.com. We will join the meeting.

**Comment by anuanju89** [comment]
@vhkilari
Hi Hemanth - We sent Teams invitation to the above email for Today (9 AM to 10 AM IST). The subject of invitation is "Mangle - Git Issue#46 - Java Method Latency Not Working". We have not received any acknowledgement or reply to the invitation.
Can you please confirm if our invitation was received?
If your team is not available during the my scheduled time, please provide your team availability - Date and Time.
I would be happy to send another invitation.

Looking Forward to Meet you and your team.

Thanks
Lakshmi P.

**Comment by vhkilari** [comment]
@anuanju89, The issue with infrastructure N/W Fault is resolved with the 3.0.0 release. Please upgrade to 3.0.0 and verify. The upgrade instructions available at
https://vmware-1.gitbook.io/mangle/mangle-administration/supported-deployment-models#upgrading-existing-instances-of-mangle .

**Comment by anuanju89** [comment]
@vhkilari - Thanks you Hemanth, will upgrade and validate the Network Latency

**Comment by vhkilari** [comment]
@anuanju89, Any updates?

**Comment by anuanju89** [comment]
The issue was tested on sample tomcat and jboss apps deployed in open shift
and we were able to successfully induce latency with out issues.
