### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by rglastra** [vmware/mangle#48]
Hi Mangle team!

Since adopting Mangle for use within our company we've had to make a number of changes.
Aside from addressing vulnerabilities this primarily required swapping out Cassandra for MySQL (we could've gone with Aerospike, but for other reasons decided to go with MySQL).

I could either publish these changes through a public fork (since they're not backwards compatible), or we could send you a PR with the changes and leave you to make that determination how best to incorporate these changes.

Is this something you would be interested in? If so, how would you like to receive the changes?

Thanks!

**Comment by aswathy-ramabhadran** [comment]
Hello @rglastra there has been enquiries about supporting other DBs but we haven't been able to get to it yet. It is great that you already have a working version of this. You can publish these changes through a public fork for now. We can provide a link to it from our public docs post the 3.0 version timeline. Let us know if it works for you.

**Comment by ashrimalivmware** [comment]
HI @rglastra,

Wanted to follow up on this if you want to publish Mangle with MySql support.

Thanks,
-Avinash

**Comment by rglastra** [comment]
Hi! I'm no longer with the company that forked it, so I can't sync it back unfortunately.

Cheers,
Robert

**Comment by ashrimalivmware** [comment]
Okay thanks Robert, let's close this ticket then.
