### ISSUE TITLE
K8s drain node attack 

### ISSUE THREAD

**Issue by ghost** [vmware/mangle#51]
Can you please add K8s drain-node attack? This will help in the K8s cluster (like in Azure) where we won't have the ability to add or remove a node from the cluster on the fly.

Thx!

**Comment by vhkilari** [comment]
@zwaris66 We will have this addressed in the future release of Mangle. If the requirement is a high priority item for you, we can help you with the implementation. The change will require only an upgrade to your mangle-default-plugin.

**Comment by zwaris66** [comment]
Thanks, Kilari! For us drain node attack is very critical. Please let me know what i need to do to make is available.

Zishan

________________________________

**Comment by vhkilari** [comment]
@zwaris66 Please forward a meeting request via zoom or MS Teams to mangle@vmware.com. I will walk you through the details.
Thanks,
    -Hemanth K

**Comment by ashrimalivmware** [comment]
Mangle 3.5 has the feature now.
