### ISSUE TITLE
Spring Service Latency Fault throws error when providing process descriptor name in "JVM Process" field

### ISSUE THREAD

**Issue by tarunmudgal** [vmware/mangle#60]
BytemanFaultTaskHelper-1615882372248-5
 FAILED
csp-app-preview
INJECTION
Executing Fault: SPRING_SERVICE_LATENCY on endpoint: csp-app-preview. More Details: [ JVMCodeLevelFa
more
Mar 16, 2021, 1:42:44 PM
Mar 16, 2021, 1:43:49 PM
ErrorCode : FI0101, ErrorMessage : Target application is not a Java process or not yet initialized. More details available in mangle log.

**Comment by tarunmudgal** [comment]
Any progress on this ticket?

**Comment by ashrimalivmware** [comment]
fixed
