### ISSUE TITLE
Installation in Kubernetes cluster is failling

### ISSUE THREAD

**Issue by johnqa** [vmware/mangle#61]
Hi, 

I am trying to deploy mangle into a Kubernetes cluster but I am not able to do so.
It fails at `kubectl -n mangle apply -f .\mangle.yaml`
First it complains that: `error: unable to recognize ".\\mangle.yaml": no matches for kind "Deployment" in version "extensions/v1"`

Than after I change magle.yaml to have `apiVersion: apps/v1` it complains that:
```
error: error validating ".\\mangle.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

 kubectl -n mangle apply -f .\mangle.yaml --validate=false
The Deployment "mangle" is invalid:
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string{"app":"mangle", "environment":"test"}: `selector` does not match template `labels`
``` 

Also I noticed that in mangle.yaml there is still mangle:2.0
```
image: mangleuser:mangle:2.0
```
Thank you,
John

**Comment by sathiyajith** [comment]
Im facing the same error. If anyone found the solution or workaround, please mention them here.

**Comment by rpraveen-vmware** [comment]
Hi @johnqa , @sathiyajith 
   Have by added the selector field and changed the api version and attached the mangle.yaml file.

The one in the github has worked in our kubernetes cluster.
The api version and certain tags will be changed according to the k8s cluster version.
Hence, please use the one in attached (rename it to mangle.yaml instead of mangle.txt).

And let us know if you are able to deploy.
   
[mangle.txt](https://github.com/vmware/mangle/files/6398146/mangle.txt)

**Comment by sathiyajith** [comment]
Is there any community channel like slack to discuss the errors and find a solution ?

**Comment by sathiyajith** [comment]
Cassandra deployment fails with the following error:

```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  15s (x3 over 75s)  default-scheduler  0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.
```

Should I remove the volume claims or what is the solution. please mention.

**Comment by rpraveen-vmware** [comment]
Hi @sathiyajith 
Seems like, 
The persistentvolume-controller has failed to find a PV with a capacity size which is equal or higher than the value that was specified in the PVC.

As per the value specified in cassandra.yaml,
resources:
        requests:
          storage: 10Gi
          
You can try giving the lesser value and deploy the cassandra pod.

Also this is the public Mangle channel:
https://join.slack.com/t/vmwmangle/shared_invite/zt-boasfe9s-zxBt9ofVRjbVFlcsy5RWAw

**Comment by ashrimalivmware** [comment]
> Hi @sathiyajith Seems like, The persistentvolume-controller has failed to find a PV with a capacity size which is equal or higher than the value that was specified in the PVC.
> 
> As per the value specified in cassandra.yaml, resources: requests: storage: 10Gi
> 
> You can try giving the lesser value and deploy the cassandra pod.
> 
> Also this is the public Mangle channel: https://join.slack.com/t/vmwmangle/shared_invite/zt-boasfe9s-zxBt9ofVRjbVFlcsy5RWAw

Closing based on Praveen's comment.
