### ISSUE TITLE
unable to do a docker installation of mangle

### ISSUE THREAD

**Issue by johnqa** [vmware/mangle#62]
Hi,

I am trying to deploy mangle using docker containers by executing the following commands in Windows (Docker Desktop):
```
run --name mangle-cassandradb -v c:/cassandra/storage/:/var/lib/cassandra -p 9042:9042 -d -e CASSANDRA_CLUSTER_NAME="manglecassandracluster" -e CASSANDRA_DC="DC1" -e CASSANDRA_RACK="rack1" -e CASSANDRA_ENDPOINT_SNITCH="GossipingPropertyFileSnitch" <internalrepo>/cassandra:3.11    


docker run --name mangle -it --rm -e DB_OPTIONS="-DcassandraContactPoints=<cassandra ip> -DcassandraSslEnabled=false -DcassandraUsername=cassandra -DcassandraPassword=cassandra" -e CLUSTER_OPTIONS="-DclusterValidationToken=mangle -DpublicAddress=127.0.0.1" -p 8080:8080 -p 8443:8443 <internalrepo>/mangleuser/mangle:3.0.0

```

Both containers are running but when trying in the browser with 127.0.0.1 for both 8080 and 8443 I get:
```
HTTP Status 404 – Not Found
```
Moreover I see no errors in the logs of mangle container.

Thank you,
John

**Comment by suprasupa** [comment]
Is this issue resolved? Please post the solution.

**Comment by rpraveen-vmware** [comment]
Hi @suprasupa 
https://localhost:8443/mangle-services/ 
is the URL to connect to mangle application through browser.

Let us know if you are able to reach this.
If not, we need to inspect on the values that you have provided for DcassandraContactPoints and others.

**Comment by ashrimalivmware** [comment]
> Hi @suprasupa https://localhost:8443/mangle-services/ is the URL to connect to mangle application through browser.
> 
> Let us know if you are able to reach this. If not, we need to inspect on the values that you have provided for DcassandraContactPoints and others.

Closing based on the comment.
