### ISSUE TITLE
what type of privilege do we need  in order to connect to vCenter to perform chaos testing

### ISSUE THREAD

**Issue by davidzengusa** [vmware/mangle#64]
we need to take advantage of the vCenter/adapter capability provided by Mangle, in order to perform vCenter/VM chaos testing,
when we setup an endpoint of vCenter in Mangle, we need to enter the user ID/password to connect to vCenter API, and vCenter administrator of our company is asking us what user ID/password we need? since he can not give us "admin" user privilege for sure, he is concerned about potential negative impact that our Mangle might have with "admin" privilege, which could affect hundreds of VMs managed in vCenter.  so, please provide detailed guidance, since we could not find relevant info from your online documentation about this feature.

**Comment by techtreet** [comment]
I had same question to mangle folks several months back on another thread and also sent email to them, but no response. Our Vcenter folks are ready to help to integrate with Vcenter but only if we can define the level of access that mangle expects from vcenter, so that they can review our request create exactly what is expected. Otherwise without such documentation about the level of access expected on Vcenter its just not possible to even consider this feature to be used.

**Comment by ashrimalivmware** [comment]
Hi @davidzengusa , @techtreet 
Details about vCenter adapter is already captured at: https://vmware-1.gitbook.io/mangle/mangle-administration/supported-deployment-models
To perform a Fault on vCenter you need to have Admin privilege, else you can't do much to inject a failure.
Document says:
The API documentation for the vCenter Adapter can be found at:
https://<NODE-IP>:<PORT>:/mangle-vc-adapter/swagger-ui.html
If this URL is accessible and reachable, then you know that the vCenter adapter is deployed and running as expected. You can proceed with the addition of the adapter to Mangle as mentioned in Adding Adapters section of the Users Guide.
The vCenter adapter requires authentication against any API calls. It supports only one user, admin. If you have use the default credentials while deploying the container then the _password is _admin. Else the password will be the custom one that you provided at the time of deployment. All the post APIs that are supported by the adapter will take the vCenter information as a request body.
