### ISSUE TITLE
Doc: README file should begin

### ISSUE THREAD

**Issue by mkbhanda** [vmware/mangle#65]
**Describe the bug**
Readme file for a project should begin with a brief  high-level explanation of its purpose.
See https://github.com/kubernetes/kubernetes  and https://github.com/grafana/grafana

**Comment by ashrimalivmware** [comment]
Thanks @mkbhanda , the introduction section has been added to readme. More details about mangle is captured at https://vmware.github.io/mangle/ which is also part of readme section.
