### ISSUE TITLE
Unable to connect docker which is hosted in the remote machine.

### ISSUE THREAD

**Issue by Monika371** [vmware/mangle#69]
![Screenshot (891)](https://user-images.githubusercontent.com/67327823/120279046-9e9e6200-c2d3-11eb-9b17-16f78d64e22b.png)
I am trying to connect docker from mangle and i am end up with this error message. Please help me out and refer the attachment.

**Comment by ashrimalivmware** [comment]
Closing this bug as we have discussed about it one of our call.
