### ISSUE TITLE
Container deployment issue

### ISSUE THREAD

**Issue by suprasupa** [vmware/mangle#71]
Hi Team,
We are trying to deploy Mangle3.0 container images in ECS Fargate. We have not done any changes to images so far. while deploying we are getting the below error for Cassandra:
Cassandra is unavailable-sleeping
Connection error:('Unable to connect to any servers'{'127.0.0.1':error(111,"Tried connecting to [(127.0.0.1,9042)].Last error:Connection refused")})

while trying from EC2 we got the same error but we can connect to Cassandra through cqlsh.
Verified the TaskDefinition with AWS support team already.

Thanks!!

**Comment by ashrimalivmware** [comment]
Hi @suprasupa could you please post the command you are running to bring the container up?

**Comment by suprasupa** [comment]
docker run --name mangle-cassandradb -v /cassandra/storage/:/var/lib/cassandra -p 9042:9042 -d -e CASSANDRA_CLUSTER_NAME="manglecassandracluster" -e CASSANDRA_DC="DC1" -e CASSANDRA_RACK="rack1" -e CASSANDRA_ENDPOINT_SNITCH="GossipingPropertyFileSnitch" <internal repo>

**Comment by suprasupa** [comment]
I am able to deploy the mangle on ECS Fargate and the above error did not affect the deployment so not thinking much as UI is up and running

**Comment by ashrimalivmware** [comment]
@suprasupa Glad it's working fine. Can we close this issue?

**Comment by suprasupa** [comment]
yes sure ..we can close the issue
