### ISSUE TITLE
Suggestion for Fault injection in ECS with Mangle

### ISSUE THREAD

**Issue by suprasupa** [vmware/mangle#73]
Hi Team,
Could you please advise if we can perform chaos scenarios for  ECS or not. If yes please guide how to proceed.

**Comment by ashrimalivmware** [comment]
HI @suprasupa ,

Are you referring Amazon Elastic Container Service here? If that is yes then Mangle don't support it right now for AWS endpoint.
Closing the ticket right now, please reopen if your query is not answered.
