### ISSUE TITLE
Mangle keeps posing for password change very frequently, not sure if this is expected behaviour. 

### ISSUE THREAD

**Issue by techtreet** [vmware/mangle#74]
**Describe the bug**
Mangle keeps posing for password change very frequently, not sure if this is expected behaviour. The user id I use is "admin"

**To Reproduce**
1. Open url https://manglenamespace/mangle-services/
2. It poses password change

**Expected behavior**
Should login the user and not pose change password screen so frequently

**Comment by ashrimalivmware** [comment]
Hi @techtreet Which version of Mangle you are using?

**Comment by techtreet** [comment]
> Hi @techtreet Which version of Mangle you are using?

its version 3.0.0

**Comment by ashrimalivmware** [comment]
@techtreet , it's always recommended to use DB persistent so please use -v option for DB container to run. eg:
docker run --name mangle-cassandradb -v /cassandra/storage/:/var/lib/cassandra -p 9042:9042 -d -e CASSANDRA_CLUSTER_NAME="manglecassandracluster" -e CASSANDRA_DC="DC1" -e CASSANDRA_RACK="rack1" -e CASSANDRA_ENDPOINT_SNITCH="GossipingPropertyFileSnitch"  mangleuser/mangle_cassandradb:<VERSION>

**Comment by ashrimalivmware** [comment]
Closing the ticket as the query is answered in the last comment.
