### ISSUE TITLE
Monitoring Tool -Integration Requirement

### ISSUE THREAD

**Issue by Monika371** [vmware/mangle#81]
Navigation: Settings-> Integration-> Metric-Providers
Similar to Datadog, and WaveFront we would like to have Applicare monitoring tool integrated with the Mangle.
Please do suggest and advice on feasibility of Applicare integration.

**Comment by vhkilari** [comment]
Metric-Providers support in mangle is provided using the Spring Micrometer integration. The integration should have been an addition of a single Meter registry support if there is out-of-the-box support from Micrometer to Applicare.
 I do not find any resources on support from micrometer to Applicare. So, here you should be first implementing the Applicare meter Registry for micrometer and we can help you with follow-up implementation in Mangle to support Applicare metric provider.

**Comment by dbhat-arkin** [comment]
Hi @Monika371 ,
Metric provider integration at Mangle provides 2 functionality :

1. Sending of fault injection events (will be sent from Mangle to configured metric provider each time when the fault is injected, remediated, completed, failed).
2. Sending mangle's application metrics to configured metric provider. This functionality will help in observing the mangle's resource usage at monitoring tool.

In the above list , item#1 (sending fault injection events) doesn't require a support from Micrometer. But, Mangle requires event API (public API) support from the Monitoring tool (in this request, it is Applicare). So, Applicare must need to have public API to send / edit and delete events. Then we will be able to implement sending of fault injection events to Applicare feature in Mangle. 

Item#2 in the above list (sending of Mangle's application metrics to Applicare) may not be feasible for now. As @vhkilari mentioned, we use Micrometer meter registry (https://github.com/micrometer-metrics/micrometer/tree/main/implementations) to publish Mangle's application metrics and Micrometer isn't supporting Applicare yet.

Thanks,
Dinesh

**Comment by ashrimalivmware** [comment]
Closing as there is no update from @Monika371 .
